name: nba
data:
  player_per_game_file: "Player Per Game.csv"
  team_summaries_file: "Team Summaries.csv"
  team_abbrev_file: "Team Abbrev.csv"
  player_totals_file: "Player Totals.csv"
  advanced_file: "Advanced.csv"
features:
  categorical:
    - player_name
    - team_abbrev
    - position
  boolean: []
  numeric:
    - season
    - age
    - games
    - games_started
    - mp_per_game
    - fg_per_game
    - fga_per_game
    - fg_percent
    - x3p_per_game
    - x3pa_per_game
    - x3p_percent
    - ft_per_game
    - fta_per_game
    - ft_percent
    - orb_per_game
    - drb_per_game
    - trb_per_game
    - ast_per_game
    - stl_per_game
    - blk_per_game
    - tov_per_game
    - pf_per_game
    - pts_per_game
targets:
  classification: is_all_star
  regression: pts_per_game
